version: '3.2'

services:

  karmabot:
    container_name: karmabot
    restart: always
    build: .
    volumes:
      - type: "mount"
        source: "/home/bomzheg/log/karmabot/"
        target: "/log"
      - type: "bind"
        source: "/home/bomzheg/sqlite/karma.db"
        target: "/karma.db"
      - type: "bind"
        source: problems
        target: "/approve.json"
    env_file: .env
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    external:
      name: nginx-revers-proxy

volumes:
  problems: