version: '3.2'

services:

  karmabot:
    container_name: karmabot
    restart: always
    depends_on:
      - redis
    build: .
    volumes:
      - type: "mount"
        source: "/home/bomzheg/log/karmabot/"
        target: "/log"
      - type: "bind"
        source: "/home/bomzheg/sqlite/karma.db"
        target: "/karma.db"
    env_file: .env
    networks:
      - reverse-proxy
      - redis

  redis:
    image: "redis:6-alpine"
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - redis

volumes:
  redis_data:

networks:
  reverse-proxy:
    external:
      name: nginx-revers-proxy
  redis: